version: '3'

services:
  android-build:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - gradle-cache:/root/.gradle
    working_dir: /app
    command: ./gradlew assembleDebug

  android-test:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - gradle-cache:/root/.gradle
    working_dir: /app
    command: ./gradlew test

volumes:
  gradle-cache: